// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDACAXzSU8faE9X0MB91a3sPf0aVCCv8zg',
    appId: '1:780703470930:web:c2c7ab6a33ce7925f2968b',
    messagingSenderId: '780703470930',
    projectId: 'notes-5a1c8',
    authDomain: 'notes-5a1c8.firebaseapp.com',
    storageBucket: 'notes-5a1c8.appspot.com',
    measurementId: 'G-0JYMT0TZ6X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7bz4Qogea2v4wItPvLWNfCbMWCKt1Rg8',
    appId: '1:780703470930:android:bb6d07010bfb2a95f2968b',
    messagingSenderId: '780703470930',
    projectId: 'notes-5a1c8',
    storageBucket: 'notes-5a1c8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzRkfECBbUXvkm5yvINa6V0uj_6fOc9_Y',
    appId: '1:780703470930:ios:d73d72c2050d16c1f2968b',
    messagingSenderId: '780703470930',
    projectId: 'notes-5a1c8',
    storageBucket: 'notes-5a1c8.appspot.com',
    iosClientId: '780703470930-ct7jr2llcaaf21bkgd0s8c64rr0s7an8.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseTodo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzRkfECBbUXvkm5yvINa6V0uj_6fOc9_Y',
    appId: '1:780703470930:ios:d73d72c2050d16c1f2968b',
    messagingSenderId: '780703470930',
    projectId: 'notes-5a1c8',
    storageBucket: 'notes-5a1c8.appspot.com',
    iosClientId: '780703470930-ct7jr2llcaaf21bkgd0s8c64rr0s7an8.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseTodo',
  );
}
